### ISSUE TITLE
0520

### ISSUE THREAD

**Issue by kyungrae** [codesquad-member-2020/airbnb-01#10]
# 오늘의 목표

- [x] 숙소 테이블에 목업 데이터 넣기
- [x]  숙소 리스트 조회를 위한 기능 구현
- [x]  배포
- [ ]  ~숙소 디테일 조회를 위한 기능 구현~

**Comment by kyungrae** [comment]
# 내일 할 일
- [ ] DTO 개발을 위한 합의 과정
- [ ] 숙소 정보를 50 개 (공공 API or 크롤링)
- [ ] 숙소 디테일

**Comment by Hyune-c** [comment]
# Fact
- 메인 화면의 json 과 배포를 성공했습니다
- 기존의 개발 방법 차이와 Dingo 가 가져온 신 구조에 대한 이해 부족으로 구조에 대한 협의가 늦어지고 있습니다
# Feelling & Feedback
- 나의 이해 부족으로 인해 수용을 못하는 것일 수 있기에 키워드를 찾아보도록 하겠습니다
- 내가 생각한 것은 코드로 짜서 시연할 수 있도록 하겠습니다
- 중간에 조금 긴 쉬는 시간이 필요할 수도 있겠다는 생각이 듭니다
- 내일부터는 뭔가 쓸 수 있는 것을 준비하겠습니다

**Comment by kyungrae** [comment]
## 사실(fact)

1. 숙박시설 조회 API를 페어를 통해 구현했다.
2. Dto 객체에 대한 합의가 아직 이루어지지 못했다.

## 느낌(Feeling)

1. 컨트롤러에서 사용되는 Dto를 공통으로 사용하는 방식은 JSP에 로직을 넣는 느낌을 받았다.
2. 기존에 읽은 책들과 의견이 달라 단의 Dto 제안이 낯설었다.

## 교훈(finding)

1. 단은 나와 다르게 빠르게 프로토타입을 만들어 보는 타입이다. 개인적으로 생각이 많고 손이 느려서 효율성이 낮은 개발자라고 생가했는데 단과 페어를 하면서 중도를 지키면서 개발을 진행하는 것 같아서 좋다.

## 향후 행동(Future action)

1. 다음 의견 불일치로 교착상태에 도달했을 때, 마스터 리뷰 요청을 통해 물어보자.

## 피드백(Feedback)

1. 단의 Dto 제안이 낯설기는 하지만 단의 근거도 합리적이라고 생가한다. 구조는 언제라도 이야기를 통해서 변경할 수 있으니 단 생각에 맞추어 개발해보자.
