### ISSUE TITLE
Geodetic System Format

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-member-2020/airbnb-01#26]
# 해야하는 이유
- 좀 더 Real 에 가까운 정보를 가져오기 위해 공공API 를 사용하였는데, 이 좌표 정보는 `WGS84` 로 되어 있습니다

# 협의 필요 사항
- 원본의 자료인 `WGS84` 포맷을 그대로 사용해도 iOS 에서는 문제가 없을 것인지?
  - 문제가 있다면 `WGS84` 를 다른 포맷으로 바꿀 것인지?
    - 포맷을 바꾼다면 
      - DB 값을 변경할 것인지?
      - iOS 에서 포맷 변경 작업을 할 것인지?
# 샘플 정보
- 아래 정보는 google map 에서 좌표가 동일함을 확인하였습니다
```json
[
  {
    "location": " 전남 담양군 금성면 새덕굴길 135-88",
    "name": "담양금성산성 오토캠핑장",
    "latitude": 35.3677151,
    "longitude": 127.0344808
  },
  {
    "location": " 전남 장흥군 부산면 지천리 260",
    "name": "깊은내 펜션",
    "latitude": 34.7521973,
    "longitude": 126.8969141
  }
]
```

**Comment by Hyune-c** [comment]
@1Consumption 
준비가 되시면 샘플 테스트 or 실 DB 데이터로 테스트 후 결과를 알려주시면 됩니다

**Comment by 1Consumption** [comment]
@Hyune-c 넵!

**Comment by Hyune-c** [comment]
@1Consumption 
현재 `특정 숙소 검색` 에는 위도, 경도 정보가 나오지만 `전체 숙소 검색` 에는 나오지 않고 있습니다
현재의 형태가 맞나요?

**Comment by 1Consumption** [comment]
해결완료
