### ISSUE TITLE
0528

### ISSUE THREAD

**Issue by 1Consumption** [codesquad-member-2020/airbnb-01#55]
# 어제 한 일

* 디테일 화면 이미지 보여주기
* 지도 연동하기

# 오늘 할 일

* 디테일 화면 나머지 정보 넣기
* 디테일 화면 공유 기능 완성하기
* 네트워크 개선하기
* 검색 조건 UI 구성하기

**Comment by kyungrae** [comment]
- 어제 한 일
   - ddd-start 완독
- 오늘 할 일
   - 개발 방향을 지금부터 바꿀지 or 기능 구현을 완성할지

**Comment by Hyune-c** [comment]
- 어제 한 일
  - 예약 기능
- 오늘 할 일
  - 페어로 DDD 구현하기
